pipelines:
  xbottrade-bot-app-deploy-test:
    group: default
    lock_behavior: none
    environment_variables:
      CLUSTER_NAME: test
      SERVICE_NAME: test
    materials:
      git:
        git: https://github.com/Dmytro-Ostapenko-97/gocd-test.git
        shallow_clone: false
        auto_update: true
        branch: dev
    stages:
      - ready-for-deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            check:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "aws ecs list-tasks --desired-status 'RUNNING' --cluster ${CLUSTER_NAME} | grep arn | sed 's/[ \"]//g'"
                    command: sh
                    run_if: passed
      - deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            deploy:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "aws ecs update-service --force-new-deployment --service ${SERVICE_NAME} --cluster ${CLUSTER_NAME} --deployment-configuration minimumHealthyPercent=0"
                    command: sh
                    run_if: passed