pipelines:
  test:
    group: test
    lock_behavior: none
    environment_variables:
      STORE_CODE: <none>
    materials:
      git:
        git: https://github.com/Dmytro-Ostapenko-97/gocd-test
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      # - terraform-destroy:
      #     fetch_materials: true
      #     keep_artifacts: false
      #     clean_workspace: true
      #     approval:
      #       type: manual
      #       allow_only_on_success: false
      #     jobs:
      #       destroy:
      #         timeout: 0
      #         elastic_profile_id: k8s-agent
      #         tasks:
      #           - exec:
      #               arguments:
      #                 - "-c"
      #                 - "cd deploy/stores/${STORE_CODE} \
      #                 && terraform init -backend-config=key=eks_infrastructure/stores/${STORE_CODE}/terraform.tfstate \
      #                 && terraform destroy -auto-approve"
      #               command: sh
      #               run_if: passed
      - jenkins-destroy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            destroy:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "curl -d STORE_CODE=${STORE_CODE} -i -X POST https://dmytro_ostapenko:XPBf3Md7MZwdts@jenkins.gregacademy.icu/job/test/buildWithParameters?token=XPBf3Md7MZwdts"
                    command: sh
                    run_if: passed
      - ecr-destroy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            destroy:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "aws ecr delete-repository --repository-name ${STORE_CODE} --force"
                    command: sh
                    run_if: passed
