pipelines:
  test:
    group: test
    lock_behavior: none
    environment_variables:
      IMAGE: dummy
      APP_NAME: dima
      NAMESPACE: application
    materials:
      git:
        git: https://github.com/Dmytro-Ostapenko-97/gocd-test
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      # - clean_workspace:
      #     fetch_materials: true
      #     keep_artifacts: false
      #     clean_workspace: true
      #     approval:
      #       type: manual
      #       allow_only_on_success: false
      #     jobs:
      #       check:
      #         timeout: 0
      #         elastic_profile_id: k8s-agent
      #         tasks:
      #           - exec:
      #               arguments:
      #                 - "-c"
      #                 - "rm -rf .terraform/"
      #               command: sh
      #               run_if: passed
      - terraform-destroy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            check:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "terraform init -reconfigure && terraform destroy -auto-approve"
                    command: sh
                    run_if: passed
      # - terraform-destroy:
      #     fetch_materials: true
      #     keep_artifacts: false
      #     clean_workspace: true
      #     approval:
      #       type: approval
      #       allow_only_on_success: true
      #     jobs:
      #       check:
      #         timeout: 0
      #         elastic_profile_id: k8s-agent
      #         tasks:
      #           - exec:
      #               arguments:
      #                 - "-c"
      #                 - "terraform init && terraform plan"
      #               command: sh
      #               run_if: passed                    
      # - terraform-destroy:
      #     fetch_materials: true
      #     keep_artifacts: false
      #     clean_workspace: true
      #     approval:
      #       type: manual
      #       allow_only_on_success: false
      #     jobs:
      #       check:
      #         timeout: 0
      #         elastic_profile_id: k8s-agent
      #         tasks:
      #           - exec:
      #               arguments:
      #                 - -c
      #                 - "terraform plan"
      #               command: sh
      #               run_if: passed