pipelines:
  test:
    group: test
    lock_behavior: none
    environment_variables:
      STORE_CODE: <none>
    materials:
      git:
        git: https://github.com/Dmytro-Ostapenko-97/gocd-test
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - terraform-destroy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: auto
            allow_only_on_success: true
          jobs:
            destroy:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "cd deploy/stores/${STORE_CODE} \
                      && terraform init -backend-config=key=eks_infrastructure/stores/${STORE_CODE}/terraform.tfstate \
                      && terraform destroy -auto-approve"
                    command: sh
                    run_if: passed
      - jenkins-destroy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          environment_variables:
            USERNAME: devops
            USER_API_TOKEN: 11dfe8e93fcdfffb1442a502ff08b227bb
            SERVER_URL: jenkins.gregacademy.icu  
          approval:
            type: auto
            allow_only_on_success: true
          jobs:
            destroy:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "curl -XPOST https://${SERVER_URL}/job/${STORE_CODE}/doDelete --user ${USERNAME}:${USER_API_TOKEN}"
                    command: sh
                    run_if: passed
      - ecr-destroy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          environment_variables:
            USERNAME: "${blablabla}"
          approval:
            type: auto
            allow_only_on_success: true
          jobs:
            destroy:
              timeout: 0
              elastic_profile_id: k8-agent-aws
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "echo ${USERNAME} && echo ${blablabla}"                     
                    command: sh
                    run_if: passed
