pipelines:
  test:
    group: test
    lock_behavior: none
    environment_variables:
      # IMAGE: dummy
      # APP_NAME: dima
      # NAMESPACE: application
    parameters: 
      STORE_CODE: STORE_CODE
    materials:
      git:
        git: https://github.com/Dmytro-Ostapenko-97/gocd-test
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      # - terraform-destroy:
      #     fetch_materials: true
      #     keep_artifacts: false
      #     clean_workspace: true
      #     approval:
      #       type: manual
      #       allow_only_on_success: false
      #     jobs:
      #       check:
      #         timeout: 0
      #         elastic_profile_id: k8s-agent
      #         tasks:
      #           - exec:
      #               arguments:
      #                 - "-c"
      #                 - "terraform init \
      #                 && terraform destroy -auto-approve"
      #               command: sh
      #               run_if: passed
      - test-parameters:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            check:
              timeout: 0
              elastic_profile_id: k8s-agent
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - "echo #{STORE_CODE} $$ echo ${APP_NAME}"
                    command: sh
                    run_if: passed  


      # - terraform-destroy:
      #     fetch_materials: true
      #     keep_artifacts: false
      #     clean_workspace: true
      #     approval:
      #       type: manual
      #       allow_only_on_success: false
      #     jobs:
      #       check:
      #         timeout: 0
      #         elastic_profile_id: k8s-agent
      #         tasks:
      #           - exec:
      #               arguments:
      #                 - -c
      #                 - "terraform plan"
      #               command: sh
      #               run_if: passed